on:
    push:
        branches:
            - main
jobs:
  version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
    
      - name: Build and push
        uses: docker/build-push-action@v6
        id: build-and-push
        with:
          push: false
          file: Dockerfile
          context: .